# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/ookkoouu/packwiz-install/cmd.version={{ .Version }}
      - -X github.com/ookkoouu/packwiz-install/cmd.cfApiKey={{ .CF_API_KEY }}

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_
      {{- replace .Os "darwin" "macos" }}_
      {{- if eq .Arch "amd64" }}x64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: "SHA256-SUMS.txt"
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^ci:"
      - "^test:"
